### PR TITLE
Handle empty string in bob.ex

### LINKED ISSUE #1: Incorrect output when input is empty string
When I feed the say() method with an empty string, I don't get the correct result.

### PR DESCRIPTION
**Pull request by itggot-linus-styren**
Fixes #1

### CODE REVIEW

**Comment by itggot-linus-styren** [comment]
Thanks for the the review @itggot-daniel-berg I will merge in your place

File: lib/bob.ex [hunk 1]
```diff
@@ -1,5 +1,5 @@
 defmodule Bob do
-  def hey(input) do
+  def say(input) do
```
Comment (itggot-linus-styren) [inline lib/bob.ex:2]: Are you sure you don't have to change the tests if you do this??

**Review by itggot-linus-styren — COMMENTED** [review]
Looks good to me overall, just a minor detail regarding the naming of function hey.
